### ISSUE TITLE
Retaining Stability - Tracker

### ISSUE THREAD

**Issue by iamyaash** [AmateursLeague/sneaky-package#189]
# Package:
## Features:
  - **Offline**:
      - [x] Show Output
      - [x] Clipboard Copy
      - [x] File Write I/O
  - **Online**:
      - [x] Clipboard Site Retrieve
      - [x] Clipboard Site Store

## Enhancement
  - **Code Optimization**:
    - [x] Offline features #185 
    - [ ] Online features 

---

## Scrips:
  - [x] `install.sh` #157 
  - [x] `build.sh` #167 

## Test Cases:
  - **Offline**:
      - [x] Show Output #135 
      - [x] Clipboard Copy #130 
      - [x] File Write I/O #165 
  - **Online**:
      - [x] Clipboard Site Retrieve #165 
      - [x] Clipboard Site Store #135

## Workflow
  - [x] **`Black`** formatter #183 
  - [x] Test Case using Pytest (manually done by owner)

## Documentation [Updated]
- [x] _Waiting for changes to be made to get updated!_

**Comment by yashksaini-coder** [comment]
> I'm a contributor under Gssoc please assign this issue with suitable labels

That's not an issue but a Project tracker. This project is completed so @Vaibhav2154 you can search for new projects to contribute to in gssoc project website

**Comment by yashksaini-coder** [comment]
Use Project dashboard for this project Much better than this @iamyaash

**Comment by iamyaash** [comment]
yes, I did created a "**Project**" for this repo and tracked all the features and changes(closed). This is more of an overview to look at, than an actual tracker.

**Comment by iamyaash** [comment]
> should have closed it long ago, but closing it now!
