### ISSUE TITLE
Documentation: Guidelines for Contributing

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#54]
Create a documentation that explains how to contribute to this project.
Although this project has relatively smaller codebase, it focusses heavily on research and implementation.

# Tasks:
- [ ] Fork this repository
- [ ] Understand the purpose of this project
- [ ] Explore it's features and methods inside `package` directory
- [ ] Report your findings in the comments section of this issue
- [ ] Propose your idea for title and sections to be included in the contribution guidelines.

Also, I'll consider changing the level from `level2` to `level3`, if you craft a perfect documentation. Take your time and work on this.

> **Note**: I will not be accepting GPT-generated answers

**Comment by this-is-yaash** [comment]
### Discussed in https://github.com/AmateursLeague/sneaky-package/discussions/53

<div type='discussions-op-text'>

<sup>Originally posted by **this-is-yaash** October  3, 2024</sup>
This discussion is **solely focussed on crafting an effective documentation**, so that the new contributors can understand without feeling overwhelmed.

Please discuss about how to create the documentation, **share your thoughts and ideas, and collaborate** on them.

We can also **pair the participants** for this task!</div>

----

Join this discussion and share your thoughts & ideas!!

**Comment by SHRAVANIc01** [comment]
i am ready to contribute.

**Comment by Wahid7852** [comment]
Can you share your ideas on how will you create an effective documentation?

**Comment by harshitpathak528** [comment]
I will clearly define the project’s purpose, goals, and key features.
Include installation instructions, usage examples, and contribution guidelines.
and provide links to any published research or related papers.
Use a table of contents for easy navigation in more detailed README.md file

Can you assign this to me

**Comment by harshitpathak528** [comment]
If you assign it, I'd be happy to start working on it.

**Comment by jindalpriyanshu101** [comment]
Those who wanna contribute, explain your approach in Discussion #53

**Comment by ShashwatAgrawal20** [comment]
@harshitpathak528 @SHRAVANIc01 are you guys still interested in working on this issue? 

IF yes kindly explain your approach in #53

**Comment by harshitpathak528** [comment]
Yes @ShashwatAgrawal20 I am still interested for making this page. 
The Page will something look like that :

1. New Contributor Guide part 
2. Getting Started section
3. Issues
   3.1 Create a New Issue
   3.2 Solve an Issue
4. Making Changes
    4.1 Make Changes in the UI
    4.2 Make Changes in a Codespace
    4.3 Make Changes Locally
5. Pull Request

And adding some more stuff according what this repo wants.
Hope so you will assign and I will start working on it

**Comment by jindalpriyanshu101** [comment]
> Yes @ShashwatAgrawal20 I am still interested for making this page. The Page will something look like that :
> 
> 1. New Contributor Guide part
> 2. Getting Started section
> 3. Issues
>    3.1 Create a New Issue
>    3.2 Solve an Issue
> 4. Making Changes
>    4.1 Make Changes in the UI
>    4.2 Make Changes in a Codespace
>    4.3 Make Changes Locally
> 5. Pull Request
> 
> And adding some more stuff according what this repo wants and points you add on tasks. Hope so you will assign and I will start working on it

Can you come to discussion thread we have opened? for further clarifications. @harshitpathak528 
Link: https://github.com/AmateursLeague/sneaky-package/discussions/53

**Comment by this-is-yaash** [comment]
Reducing the label to **`level1`**, as the Project Admins were instructed to use only **`level1`** labels for documentation!

> From GSSoC'24 Extd!

**Comment by tannuiscoding** [comment]
> Create a documentation that explains how to contribute to this project. Although this project has relatively smaller codebase, it focusses heavily on research and implementation.
> 
> # Tasks:
> * [ ]  Fork this repository
> * [ ]  Understand the purpose of this project
> * [ ]  Explore it's features and methods inside `package` directory
> * [ ]  Report your findings in the comments section of this issue
> * [ ]  Propose your idea for title and sections to be included in the contribution guidelines.
> 
> Also, I'll consider changing the level from `level2` to `level3`, if you craft a perfect documentation. Take your time and work on this.
> 
> > **Note**: I will not be accepting GPT-generated answers

I can do this documentation. The structure for my document is going to be like this:

1. How to download and run the project 
2. How to raise an issue
3. How to fork the repo
4. How to clone the repo and start working 
5. How and where to commit
6. How to make a pull request.

**Comment by this-is-yaash** [comment]
#53 Use this discussion channel please!
@tannuiscoding

**Comment by softcreations01** [comment]
> Create a documentation that explains how to contribute to this project. Although this project has relatively smaller codebase, it focusses heavily on research and implementation.
> 
> # Tasks:
> * [ ]  Fork this repository
> * [ ]  Understand the purpose of this project
> * [ ]  Explore it's features and methods inside `package` directory
> * [ ]  Report your findings in the comments section of this issue
> * [ ]  Propose your idea for title and sections to be included in the contribution guidelines.
> 
> Also, I'll consider changing the level from `level2` to `level3`, if you craft a perfect documentation. Take your time and work on this.
> 
> > **Note**: I will not be accepting GPT-generated answers

I would like to work on this issue under GSSoC'24 Extended Edition and I'd explain how I intend to do this in the discussion page

**Comment by softcreations01** [comment]
Yes, okay with me. @this-is-yaash

**Comment by this-is-yaash** [comment]
@softcreations01 you are assigned!
tomorrow 9 AM, is the deadline for this!
