### ISSUE TITLE
Documentation: General Documentation

### ISSUE THREAD

**Issue by this-is-yaash** [AmateursLeague/sneaky-package#55]
**Create a comprehensive documentation that explains how to get started on this package. It should cover essential aspects of the project, including how to get started, how to execute the project, purpose, license, and any additional sections you think would add value.**

# Tasks:
- [ ] Fork this repository
- [ ] Understand the purpose of this project
- [ ] Explore it's features and methods inside `package` directory
- [ ] Report your findings in the comments section of this issue
- [ ] Propose your idea for title and sections to be included in the documentation.

> **Note**: I will not be accepting GPT-generated answers, take your time and work on this.

**Comment by Muskan-bhatt249** [comment]
@this-is-yaash I think I am capable of doing this task and provide you with a enhanced documentation. I have gone through your project and have some ideas for the documentations, we can add sections like 

- Project Overview 
- Key Features 
- Technologies used
- Licence 
- How to Contribute to this project (all the steps to fork the repository and cloning it to device till how to make a PR )
- Contribution Points (Describing how different levels would provides points)
- GSSoC-Ext Guidelines 
- Ending Note

My understanding of the project:
The project basically deals with the possible risks that user can face due to the vulnerabilities of pip package. The code can be installed in a device just like normal python package, but can lead to leak in sensitive information, virus or malware in your device. The project wants to highlight the drawbacks of pip package security.

**Comment by jindalpriyanshu101** [comment]
Your implementation idea seems promising, you're assigned @Muskan-bhatt249. Make sure to keep things visually appealing.

**Comment by this-is-yaash** [comment]
### Discussed in https://github.com/AmateursLeague/sneaky-package/discussions/59

<div type='discussions-op-text'>

<sup>Originally posted by **this-is-yaash** October  3, 2024</sup>
Please share your progress, ideas, and thoughts in the discussion channel. Don’t try to do everything on your own(_we might be able to help you_), let others know what you’re working on and thinking. Together, as a team, we can create the best documentation.</div>

---

Please use this discussion channel to share updates on your progress, ideas and thoughts!

**Comment by this-is-yaash** [comment]
@Muskan-bhatt249 any updates?

**Comment by this-is-yaash** [comment]
@Muskan-bhatt249 Could you please provide any updates on your progression?

**Comment by tannuiscoding** [comment]
> **Create a comprehensive documentation that explains how to get started on this package. It should cover essential aspects of the project, including how to get started, how to execute the project, purpose, license, and any additional sections you think would add value.**
> 
> # Tasks:
> * [ ]  Fork this repository
> * [ ]  Understand the purpose of this project
> * [ ]  Explore it's features and methods inside `package` directory
> * [ ]  Report your findings in the comments section of this issue
> * [ ]  Propose your idea for title and sections to be included in the documentation.
> 
> > **Note**: I will not be accepting GPT-generated answers, take your time and work on this.


I can write the documentation for this code.
These are the things that I'll include. Feel free to add or remove according to your needs. 

1- project overview 
2- what is the project about
3- steps to contribute
4- how to run this project 
5- how to test the code.

Kindly assign me this issue under GSsoc'24 ext.

**Comment by this-is-yaash** [comment]
Reducing the label to **`level1`**, as the Project Admins were instructed to use only **`level1`** labels for documentation!

> From GSSoC'24 Extd!

**Comment by ShashwatAgrawal20** [comment]
@Muskan-bhatt249 hey, are you still working on this? I think you already past the deadline. you'll be unassigned from the issue if you don't reply by 1.

**Comment by Muskan-bhatt249** [comment]
@ShashwatAgrawal20 I am working on it I will provide my PR in some time.

**Comment by Muskan-bhatt249** [comment]
Can you please just mention who is the project Admin so that I can Mention him/her in the documentation

**Comment by Wahid7852** [comment]
@this-is-yaash is the PA

**Comment by Muskan-bhatt249** [comment]
@this-is-yaash @ShashwatAgrawal20 @jindalpriyanshu101 All the promised changes are made and I have created a PR for it. Please provide feedback on what changes need to be made. I have added additional sections for Contributors badges -Hope you like it.

**Comment by yasheela-alla** [comment]
@this-is-yaash I have crafted the document for issue #67, I have raised a PR ( I forgot that i was not assigned yet ), Please check sir.

**Comment by Muskan-bhatt249** [comment]
@this-is-yaash and @ShashwatAgrawal20 Can you please help with the PR, I have created it 2 times but every time it is getting a conflict, I tried all the ways I know to solve it but still the same problem in 2nd PR as well. Please guide what to do

**Comment by this-is-yaash** [comment]
@Muskan-bhatt249 your doc is good!
please update the 9 changes I have mentioned in the review changes, then we'll get it merged!

**Comment by Muskan-bhatt249** [comment]
@this-is-yaash I have done the changes that you mentioned

**Comment by Muskan-bhatt249** [comment]
@this-is-yaash PR #81

**Comment by this-is-yaash** [comment]
@Muskan-bhatt249 thanks, I'll review the changes and let you know!

**Comment by this-is-yaash** [comment]
#81 @Muskan-bhatt249 
please make the final changes, and we'll merge it!
